import Head from "next/head";
import Script from "next/script";

const HtmlHeader = () => {
  return (
    <>
      <Head>
        <title>petBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        async
        type="text/javascript"
        src="https://dapi.kakao.com/v2/maps/sdk.js?appkey=d5c682ad42a1b2dc53379222a3b46761&autoload=false"
      />
    </>
  );
};

export default HtmlHeader;
