import Head from "next/head";
import Script from "next/script";

const HtmlHead = ({ currentPath }: { currentPath: string }) => {
  return (
    <>
      <Head>
        <title>petBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          as="style"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css"
        />
        <link
          className="Kakao__Pre"
          rel={`${
            currentPath.includes("hospitalmap") ? "preload" : "prefetch"
          }`}
          as="text/javascript"
          href="https://dapi.kakao.com/v2/maps/sdk.js?appkey=d5c682ad42a1b2dc53379222a3b46761&libraries=services,clusterer&autoload=false"
        />
      </Head>
    </>
  );
};

export default HtmlHead;
