import Head from "next/head";
import Script from "next/script";

const HtmlHeader = () => {
  return (
    <Head>
      <title>petBook</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <script
        type="text/javascript"
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=d5c682ad42a1b2dc53379222a3b46761"
      ></script>
      <script
        type="text/javascript"
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=APIKEY&libraries=services,clusterer,drawing"
      ></script>
    </Head>
  );
};

export default HtmlHeader;
