name: Auto Assign

on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: .github/auto-assign.yml
