name: CD Story Book
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - dev

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.26.3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}

  cd-notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - deploy-production
    if: ${{ always() }}
    steps:
      - name: cd-notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.UPDATE_WEBHOOK }}
          username: 'petBot'
          avatar-url: 'https://cdn.discordapp.com/app-icons/1044621624864940163/87fe18353f90a7a4c275be945afc14e5.png?size=512'
          title: '${{ github.workflow }} : ${{ github.event_name }}'
          description: "🚥 상태 : {{STATUS}}\n🔍 로그 확인 : 제목을 클릭하세요\n"
          include-details: 'false'
          color-success: '#008d62'
          color-failure: '#9b111e'
          color-cancelled: '#ffd400'
