name: petbook frontend Node.js CI

# 구독할 이벤트
on:
  workflow_dispatch:
  push:
    branches: [main, github-action-ci]
  pull_request:
    branches: [main]

# jobs 단위로 개별 서버(정확히는 Docker 컨테이너 단위라고 한다.)에서 작업이 수행된다.
# 각 작업은 병렬로 실행 된다고 하는데, needs: build와 같이 표시해서 기다릴 수도 있다.
jobs:
  build:
    # Ubuntu, Windows, MacOS를 지원한다.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: ./petbook_fe
      - name: yarn run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: ./petbook_fe
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
