name: petBook StoryBook CD
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_STORYBOOK_ID }}
  NEXT_PUBLIC_STORAGE: ${{ secrets.NEXT_PUBLIC_STORAGE }}
  NEXT_PUBLIC_TESTER: ${{ secrets.NEXT_PUBLIC_TESTER }}

on:
  push:
    branches:
      - dev

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install PNPM
        run: npm install --global pnpm@7.26.3
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
      - name: Build Storybook Artifacts
        run: |
          pnpm install
          NEXT_PUBLIC_STORAGE=${{ secrets.NEXT_PUBLIC_STORAGE }} pnpm build-storybook
          cd ./storybook-static
      - name: Deploy Storybook Artifacts to Vercel
        run: vercel --prod --yes ./storybook-static --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
