name: Preview Story Book
env:
  VERCEL_ORG_ID: ${{ secrets.PREVIEW_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PREVIEW_VERCEL_PROJECT_STORYBOOK_ID }}
  NEXT_PUBLIC_STORAGE: ${{ secrets.NEXT_PUBLIC_STORAGE }}
  NEXT_PUBLIC_TESTER: ${{ secrets.NEXT_PUBLIC_TESTER }}

on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    if: github.event.action != 'closed'
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/story-book'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  deploy-production:
    runs-on: ubuntu-latest
    needs: check-comment
    if: needs.check-comment.outputs.triggered == 'true'

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install Yarn
        run: npm install --global yarn
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.PREVIEW_VERCEL_DEPLOY_TOKEN }}
      - name: Build Storybook Artifacts
        run: |
          yarn install
          NEXT_PUBLIC_STORAGE=${{ secrets.NEXT_PUBLIC_STORAGE }} yarn build-storybook
          cd ./storybook-static
      - name: Deploy Storybook Artifacts to Vercel
        run: vercel --prod --yes ./storybook-static --token=${{ secrets.PREVIEW_VERCEL_DEPLOY_TOKEN }}

      - name: Comment On PR
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: |-
            [story-book link](https://pet-book-stroy-book.vercel.app/)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
