name: Preview Story Book
env:
  VERCEL_ORG_ID: ${{ secrets.PREVIEW_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PREVIEW_VERCEL_PROJECT_STORYBOOK_ID }}

on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    if: github.event.action != 'closed'
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/story-book'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  deploy-production:
    runs-on: ubuntu-latest
    needs: check-comment
    if: needs.check-comment.outputs.triggered == 'true'

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.6.6

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.PREVIEW_VERCEL_DEPLOY_TOKEN }}
      - name: Build Storybook Artifacts
        run: |
          pnpm install
          NEXT_PUBLIC_STORAGE=${{ secrets.NEXT_PUBLIC_STORAGE }} pnpm build-storybook
          cd ./storybook-static
      - name: Deploy Storybook Artifacts to Vercel
        run: vercel --prod --yes ./storybook-static --token=${{ secrets.PREVIEW_VERCEL_DEPLOY_TOKEN }}

      - name: Comment On PR
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: |-
            [story-book link](https://pet-book-stroy-book.vercel.app/)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cd-notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - deploy-production
    if: ${{ always() }}
    steps:
      - name: cd-notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.UPDATE_WEBHOOK }}
          username: 'petBot'
          avatar-url: 'https://cdn.discordapp.com/app-icons/1044621624864940163/87fe18353f90a7a4c275be945afc14e5.png?size=512'
          title: '${{ github.workflow }} : ${{ github.event_name }}'
          description: "🚥 상태 : {{STATUS}}\n🔍 로그 확인 : 제목을 클릭하세요\n"
          include-details: 'false'
          color-success: '#008d62'
          color-failure: '#9b111e'
          color-cancelled: '#ffd400'
