name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  problem-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.26.3

      - name: Install dependencies
        run: pnpm install

      - name: Lint Check
        run: pnpm lint

      - name: Build Project Artifacts
        run: pnpm build

      - uses: ArtiomTr/jest-coverage-report-action@v2

  vercel-check-web-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.26.3

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}

  vercel-check-story-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.26.3

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
      - name: Build Storybook Artifacts
        run: |
          pnpm install
          NEXT_PUBLIC_STORAGE=${{ secrets.NEXT_PUBLIC_STORAGE }} pnpm build-storybook
          cd ./storybook-static

  comment-failure:
    name: Comment Failure
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs:
      - problem-check
      - vercel-check-web-client
      - vercel-check-story-book
    if: ${{ failure() }}
    steps:
      - uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: |-
            CI 실패
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
